# theme = "jetbrains_dark"
# theme = "gruvbox-material"
theme = "onelight"

[editor]
line-number = "relative"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
cursorline = true
true-color = true
mouse = true
